import { ApiProperty } from "@nestjs/swagger";
import { User } from "src/server/user/entities/user.entity";

export class LoginResponseDto {
  @ApiProperty({
    description: "JWT generated by login",
    example: "AUTOMATICALLY GENERATED TOKEN",
  })
  token: string;

  @ApiProperty({
    description: "Authenticated user data",
  })
  user: User;
}
